language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t complexclient-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true complexclient-dev npm run test

after_success:
  - docker build -t naveen4141/complex-multi-client ./client
#  - docker build -t naveen4141/complex-multi-server ./server
#  - docker build -t naveen4141/complex-multi-nginx ./nginx
#  - docker build -t naveen4141/complex-multi-worker ./worker

# docker hub image push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push naveen4141/complex-multi-client
#  - docker push naveen4141/complex-multi-server
#  - docker push naveen4141/complex-multi-nginx
#  - docker push naveen4141/complex-multi-worker
