language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t complexclient-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run e CI=true complexclient-dev npm run test

after_success:
  - docker build -t complex-multi-client ./client
  - docker build -t complex-multi-server ./server
  - docker build -t complex-multi-nginx ./nginx
  - docker build -t complex-multi-worker ./worker

# docker hub image push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push complex-multi-client
  - docker push complex-multi-nginx
  - docker push complex-multi-server
  - docker push complex-multi-worker

